-- MySQL Script generated by MySQL Workbench
-- Mon Sep 19 18:25:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema hospitals_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema hospitals_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hospitals_db` DEFAULT CHARACTER SET utf8 ;
USE `hospitals_db` ;

-- -----------------------------------------------------
-- Table `hospitals_db`.`hospitals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`hospitals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`patients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`patients` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `dob` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_patients_hospitals_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_patients_hospitals`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospitals_db`.`hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`departments` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`doctors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`doctors` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  `specification` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`diseases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`diseases` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `doctor_id` BIGINT UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_diseases_hospitals1_idx` (`hospital_id` ASC) VISIBLE,
  INDEX `fk_diseases_departments1_idx` (`department_id` ASC) VISIBLE,
  INDEX `fk_diseases_doctors1_idx` (`doctor_id` ASC) VISIBLE,
  CONSTRAINT `fk_diseases_hospitals1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospitals_db`.`hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diseases_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospitals_db`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diseases_doctors1`
    FOREIGN KEY (`doctor_id`)
    REFERENCES `hospitals_db`.`doctors` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`headPhysicians`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`headPhysicians` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(50) NOT NULL,
  `last_name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_headPhysicians_hospitals1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_headPhysicians_hospitals1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospitals_db`.`hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`employees` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hospital_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_staff_hospitals1_idx` (`hospital_id` ASC) VISIBLE,
  CONSTRAINT `fk_staff_hospitals1`
    FOREIGN KEY (`hospital_id`)
    REFERENCES `hospitals_db`.`hospitals` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`department_employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`department_employee` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_departments_has_staff_staff1_idx` (`employee_id` ASC) VISIBLE,
  INDEX `fk_departments_has_staff_departments1_idx` (`department_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_departments_has_staff_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospitals_db`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_staff_staff1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hospitals_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`contacts` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `employee_id` BIGINT UNSIGNED NOT NULL,
  `passport` VARCHAR(50) NOT NULL,
  `phone_number` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contacts_patients1_idx` (`patient_id` ASC) VISIBLE,
  INDEX `fk_contacts_employees1_idx` (`employee_id` ASC) VISIBLE,
  CONSTRAINT `fk_contacts_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospitals_db`.`patients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contacts_employees1`
    FOREIGN KEY (`employee_id`)
    REFERENCES `hospitals_db`.`employees` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`reception_hours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`reception_hours` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `reception` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`cards` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `patient_id` BIGINT UNSIGNED NOT NULL,
  `number` INT NOT NULL,
  `registration` DATE NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cards_patients1_idx` (`patient_id` ASC) VISIBLE,
  CONSTRAINT `fk_cards_patients1`
    FOREIGN KEY (`patient_id`)
    REFERENCES `hospitals_db`.`patients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hospitals_db`.`department_reception_hour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `hospitals_db`.`department_reception_hour` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `department_id` BIGINT UNSIGNED NOT NULL,
  `reception_hour_id` BIGINT UNSIGNED NOT NULL,
  INDEX `fk_departments_has_receptions_hours_receptions_hours1_idx` (`reception_hour_id` ASC) VISIBLE,
  INDEX `fk_departments_has_receptions_hours_departments1_idx` (`department_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_departments_has_receptions_hours_departments1`
    FOREIGN KEY (`department_id`)
    REFERENCES `hospitals_db`.`departments` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_receptions_hours_receptions_hours1`
    FOREIGN KEY (`reception_hour_id`)
    REFERENCES `hospitals_db`.`reception_hours` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
